#!/usr/bin/env bash
# Checking  if less than 3 parameters passed
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# assigning each arguments with variable

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4


#  transfer the file to the user home directory
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Check the transfer
if [ $? -eq 0 ]
then
  echo "File transfer succeded"
else
  echo "File transfer failed"
fi
