#!/usr/bin/env bash

# Update packages
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create index.html
echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

# Perform a 301 Redirection
redirection_config="server_name _;\n\trewrite ^/redirect_me https://github.com/Yosrahabouria permanent;"
sudo sed -i "/server_name _;/a $redirection_config" /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart
