#!/usr/bin/env bash                                                        
# Server-01 login commands                          

# Set the SSH agent                                              
eval $("ssh-agent")

# Path to identityFile                                    
ssh-add ~/.ssh/school

# Username and IP Address                                                
ssh ubuntu@54.100.26.223.96
