#!/usr/bin/env bash
#Install and configure HAproxy

sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver web-01 54.100.26.223:80 check\n\tserver web-02 54.100.26.223:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
