#!/usr/bin/env bash
# script displaying 4-to_infinity_and_beyond process idefinetly
# With a sleep 2 in between each iteration
while true
do
  trap 'echo "I am invincible!!!"' 15
  echo "To infinity and beyond"
  sleep 2
done
