#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and Hi the 9th

#initialisation of counter
i=0

#use the while loop
while [ "$i" -lt 10 ]
do
	echo "Best School"
	if [ "$i" -eq 8 ]
	then
		echo "Hi"
	fi
        ((i += 1))
done
