#!/usr/bin/env bash
# This script is displaying sentences based on the loop

#initialisation of counter
i=0

#use the while loop
while [ "$i" -le 10 ]
do
  if  [[ "$i" -eq 4 ]]
     then
             echo "bad luck"
  elif  [[ "$i" -eq 8 ]]
     then
             echo "good luck"
  else
             echo "Best School"
  fi

       ((i++))
done

