#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20

#initialisation of counter
i=0

#use the while loop
while [ "$i" -le 20 ]
do
	case $i in
		4)
			echo "4"
			echo "bad luck from China"
			;;
		9)
			echo "9"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac

	((i++))
done
